package ch.uzh.csg.reimbursement.model;

public enum ExpenseState {

	DRAFT, ASSIGNED_TO_PROFESSOR, ASSIGNED_TO_FINANCE_ADMIN, ACCEPTED, REJECTED, PRINTED, SIGNED_BY_USER, SIGNED_BY_PROF, SIGNED_BY_FINANCE_ADMIN;

}
