package ch.uzh.csg.reimbursement.model;

public enum ExpenseState {

	DRAFT,
	ASSIGNED_TO_PROFESSOR,
	ASSIGNED_TO_FINANCE_ADMIN,
	ACCEPTED,
	REJECTED,
	PRINTED,
	TO_SIGN_BY_USER,
	TO_SIGN_BY_PROFESSOR,
	TO_SIGN_BY_FINANCE_ADMIN;

}
